spring:
  application:
    name: repo-content-generator

gg:
  jte:
    developmentMode: true

app:
  output:
    directory: output

github:
  token: ${GITHUB_TOKEN}
  includePatterns:
    - "**/*.md"
    - "**/*.txt"
    - "**/*.xml"
    - "**/*.java"
    - "**/*.jte"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.graphqls"
    - "**/*.properties"
    - "**/*.js"
    - "**/*.css"
    - "**/*.scss"
  excludePatterns:
    - ".mvn/**"
    - ".idea/**"
    - "target/**"
    - ".gitignore"
    - ".gitattributes"
    - "mvnw"
    - "mvnw.cmd"

logging:
  level:
    dev:
      danvega: debug